package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"liaf/pkg/toolchain"
	"liaf/pkg/typst/packages"
)

// Arquivo de trava dos pacotes Typst, ao lado do .liaf (versionar, como o go.sum).
const typstLockName = "liaf-typst.lock"

// embedTypstPackages embute no programa os pacotes do Typst Universe que ele cita
// (@preview/nome:versão), para que os documentos rodem offline dentro do binário (#034).
// Só age se o programa usa o motor de documentos. Baixa na primeira vez (com cache e SHA-256
// conferido no arquivo de trava) e grava os pacotes em app.Dir/typstpkgs, com um init() que
// os registra no runtime.
func embedTypstPackages(app *toolchain.App, generatedCode, srcPath string) error {
	if !strings.Contains(generatedCode, `"liaf/pkg/docrt"`) {
		return nil
	}
	var texts = []string{generatedCode}
	if src, err := os.ReadFile(srcPath); err == nil {
		texts = append(texts, string(src)) // pega também citações em comentários
	}
	// Documentos Typst lidos em tempo de execução (fs-read-file) ficam ao lado do .liaf.
	typs, _ := filepath.Glob(filepath.Join(filepath.Dir(srcPath), "*.typ"))
	for _, p := range typs {
		if b, err := os.ReadFile(p); err == nil {
			texts = append(texts, string(b))
		}
	}
	specs := packages.Scan(texts...)
	if len(specs) == 0 {
		return nil
	}

	cache, err := typstPackageCache()
	if err != nil {
		return err
	}
	lockFile := filepath.Join(filepath.Dir(srcPath), typstLockName)
	lock, err := packages.ReadLock(lockFile)
	if err != nil {
		return err
	}
	before := len(lock)
	r := &packages.Resolver{Cache: cache, Lock: lock}
	all, err := r.Resolve(specs)
	if err != nil {
		return err
	}
	if len(lock) != before {
		if err := packages.WriteLock(lockFile, lock); err != nil {
			return fmt.Errorf("gravar %s: %w", lockFile, err)
		}
	}

	dst := filepath.Join(app.Dir, "typstpkgs")
	for _, s := range all {
		if err := copyDirectory(r.Path(s), filepath.Join(dst, filepath.FromSlash(s.Dir()))); err != nil {
			return fmt.Errorf("embutir %s: %w", s, err)
		}
		fmt.Printf("📦 [LIAF Doc] pacote %s embutido\n", s)
	}
	const initGo = `// Code generated by liafc. DO NOT EDIT.
package main

import (
	"embed"

	liafdoc "liaf/pkg/docrt"
)

//go:embed all:typstpkgs
var _liafTypstPackages embed.FS

func init() {
	if err := liafdoc.RegisterPackages(_liafTypstPackages, "typstpkgs"); err != nil {
		panic("pacotes Typst embutidos: " + err.Error())
	}
}
`
	return os.WriteFile(filepath.Join(app.Dir, "typst_packages.go"), []byte(initGo), 0o644)
}

// typstPackageCache é a pasta onde os pacotes baixados ficam entre builds.
func typstPackageCache() (string, error) {
	if dir := os.Getenv("LIAF_TYPST_PACKAGES"); dir != "" {
		return filepath.Abs(dir)
	}
	base, err := os.UserCacheDir()
	if err != nil {
		return "", fmt.Errorf("sem pasta de cache para pacotes Typst (defina LIAF_TYPST_PACKAGES): %w", err)
	}
	return filepath.Join(base, "liaf", "typst-packages"), nil
}

// Famílias de fonte do motor de documentos (pkg/typst/fonts). Cada uma pode ser excluída do
// binário com a build tag liaf_doc_sem_<id>.
var docFontFamilies = []string{"inter", "serif", "math", "mono"}

// docFontTags converte --doc-fonts=inter,math nas tags que excluem as demais famílias.
// Vazio mantém todas.
func docFontTags(list string) ([]string, error) {
	if strings.TrimSpace(list) == "" {
		return nil, nil
	}
	keep := map[string]bool{}
	for _, f := range strings.Split(list, ",") {
		f = strings.TrimSpace(f)
		if !slices.Contains(docFontFamilies, f) {
			return nil, fmt.Errorf("--doc-fonts: família desconhecida %q (use %s)", f, strings.Join(docFontFamilies, ", "))
		}
		keep[f] = true
	}
	var tags []string
	for _, f := range docFontFamilies {
		if !keep[f] {
			tags = append(tags, "liaf_doc_sem_"+f)
		}
	}
	return tags, nil
}
