package codegen

import (
	"fmt"
	"strings"

	"liaf/pkg/ast"
)

type Generator struct {
	prog   *ast.Program
	sb     strings.Builder
	indent int
}

func New(prog *ast.Program) *Generator {
	return &Generator{prog: prog}
}

func (g *Generator) Generate() string {
	g.sb.WriteString("// Code generated by liafc (Language for AI First). DO NOT EDIT.\n")
	g.sb.WriteString("package main\n\n")
	g.sb.WriteString("import (\n")
	g.sb.WriteString("\t\"fmt\"\n")
	g.sb.WriteString("\t\"io\"\n")
	g.sb.WriteString("\t\"net/http\"\n")
	g.sb.WriteString("\t\"time\"\n")
	g.sb.WriteString("\t\"liaf/pkg/web\"\n")
	g.sb.WriteString(")\n\n")

	// Built-in helper functions
	g.sb.WriteString("func _liaf_concat(args ...interface{}) string {\n")
	g.sb.WriteString("\tres := \"\"\n")
	g.sb.WriteString("\tfor _, a := range args {\n")
	g.sb.WriteString("\t\tres += fmt.Sprint(a)\n")
	g.sb.WriteString("\t}\n")
	g.sb.WriteString("\treturn res\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_str(v interface{}) string {\n")
	g.sb.WriteString("\treturn fmt.Sprint(v)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_sleep_ms(ms int64) {\n")
	g.sb.WriteString("\ttime.Sleep(time.Duration(ms) * time.Millisecond)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_http_get(url string) string {\n")
	g.sb.WriteString("\tresp, err := http.Get(url)\n")
	g.sb.WriteString("\tif err != nil {\n")
	g.sb.WriteString("\t\treturn fmt.Sprintf(\"{\\\"error\\\": %q}\", err.Error())\n")
	g.sb.WriteString("\t}\n")
	g.sb.WriteString("\tdefer resp.Body.Close()\n")
	g.sb.WriteString("\tb, _ := io.ReadAll(resp.Body)\n")
	g.sb.WriteString("\treturn string(b)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_http_serve(addr string, handler func(string) string) {\n")
	g.sb.WriteString("\thttp.HandleFunc(\"/\", func(w http.ResponseWriter, r *http.Request) {\n")
	g.sb.WriteString("\t\tres := handler(r.URL.Path)\n")
	g.sb.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	g.sb.WriteString("\t\tfmt.Fprint(w, res)\n")
	g.sb.WriteString("\t})\n")
	g.sb.WriteString("\tif err := http.ListenAndServe(addr, nil); err != nil {\n")
	g.sb.WriteString("\t\tfmt.Printf(\"HTTP Server Error: %v\\n\", err)\n")
	g.sb.WriteString("\t}\n")
	g.sb.WriteString("}\n\n")

	for _, decl := range g.prog.Decls {
		switch d := decl.(type) {
		case *ast.StructDecl:
			g.genStruct(d)
		case *ast.FuncDecl:
			g.genFunc(d)
		}
	}

	return g.sb.String()
}

func (g *Generator) genStruct(s *ast.StructDecl) {
	g.sb.WriteString(fmt.Sprintf("type %s struct {\n", s.Name))
	for _, f := range s.Fields {
		g.sb.WriteString(fmt.Sprintf("\t%s %s\n", f.Name, mapType(f.Type)))
	}
	g.sb.WriteString("}\n\n")
}

func (g *Generator) genFunc(f *ast.FuncDecl) {
	ret := mapType(f.ReturnType)
	if ret != "" {
		ret = " " + ret
	}

	params := []string{}
	for _, p := range f.Params {
		params = append(params, fmt.Sprintf("%s %s", p.Name, mapType(p.Type)))
	}

	g.sb.WriteString(fmt.Sprintf("func %s(%s)%s {\n", f.Name, strings.Join(params, ", "), ret))
	g.indent++

	for _, stmt := range f.Body {
		g.genStmt(stmt)
	}

	g.indent--
	g.sb.WriteString("}\n\n")
}

func (g *Generator) genStmt(s ast.Stmt) {
	g.writeIndent()

	switch node := s.(type) {
	case *ast.LetStmt:
		g.sb.WriteString(fmt.Sprintf("%s := %s\n", node.Name, g.genExpr(node.Value)))
	case *ast.ReturnStmt:
		if node.Value != nil {
			g.sb.WriteString(fmt.Sprintf("return %s\n", g.genExpr(node.Value)))
		} else {
			g.sb.WriteString("return\n")
		}
	case *ast.SpawnStmt:
		g.sb.WriteString(fmt.Sprintf("go %s\n", g.genCall(node.Call)))
	case *ast.SendStmt:
		g.sb.WriteString(fmt.Sprintf("%s <- %s\n", g.genExpr(node.Channel), g.genExpr(node.Value)))
	case *ast.IfStmt:
		g.sb.WriteString(fmt.Sprintf("if %s {\n", g.genExpr(node.Condition)))
		g.indent++
		for _, sub := range node.ThenBody {
			g.genStmt(sub)
		}
		g.indent--
		if len(node.ElseBody) > 0 {
			g.writeIndent()
			g.sb.WriteString("} else {\n")
			g.indent++
			for _, sub := range node.ElseBody {
				g.genStmt(sub)
			}
			g.indent--
		}
		g.writeIndent()
		g.sb.WriteString("}\n")
	case *ast.ExprStmt:
		g.sb.WriteString(fmt.Sprintf("%s\n", g.genExpr(node.Expression)))
	case *ast.RecvExpr:
		g.sb.WriteString(fmt.Sprintf("<-%s\n", g.genExpr(node.Channel)))
	}
}

func (g *Generator) genExpr(e ast.Expr) string {
	if e == nil {
		return ""
	}

	switch node := e.(type) {
	case *ast.IntLiteral:
		return fmt.Sprintf("%d", node.Value)
	case *ast.FloatLiteral:
		return fmt.Sprintf("%f", node.Value)
	case *ast.StringLiteral:
		return fmt.Sprintf("%q", node.Value)
	case *ast.BoolLiteral:
		return fmt.Sprintf("%t", node.Value)
	case *ast.IdentifierExpr:
		return node.Name
	case *ast.RecvExpr:
		return fmt.Sprintf("<-%s", g.genExpr(node.Channel))
	case *ast.BinaryOpExpr:
		opSymbol := mapOp(node.Op)
		return fmt.Sprintf("(%s %s %s)", g.genExpr(node.Left), opSymbol, g.genExpr(node.Right))
	case *ast.CallExpr:
		return g.genCall(node)
	}

	return ""
}

func (g *Generator) genCall(call *ast.CallExpr) string {
	switch call.Fn {
	case "println":
		args := []string{}
		for _, a := range call.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("fmt.Println(%s)", strings.Join(args, ", "))
	case "print":
		args := []string{}
		for _, a := range call.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("fmt.Print(%s)", strings.Join(args, ", "))
	case "concat":
		args := []string{}
		for _, a := range call.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("_liaf_concat(%s)", strings.Join(args, ", "))
	case "str":
		if len(call.Args) > 0 {
			return fmt.Sprintf("_liaf_str(%s)", g.genExpr(call.Args[0]))
		}
		return "\"\""
	case "sleep_ms":
		if len(call.Args) > 0 {
			return fmt.Sprintf("_liaf_sleep_ms(%s)", g.genExpr(call.Args[0]))
		}
		return ""
	case "make_chan":
		if len(call.Args) > 0 {
			if ident, ok := call.Args[0].(*ast.IdentifierExpr); ok {
				return fmt.Sprintf("make(chan %s)", mapType(ident.Name))
			}
		}
		return "make(chan interface{})"
	case "http_serve":
		if len(call.Args) >= 2 {
			return fmt.Sprintf("_liaf_http_serve(%s, %s)", g.genExpr(call.Args[0]), g.genExpr(call.Args[1]))
		}
		return ""
	case "http_get":
		if len(call.Args) >= 1 {
			return fmt.Sprintf("_liaf_http_get(%s)", g.genExpr(call.Args[0]))
		}
		return "\"\""
	case "serve_site":
		dir := "\"./public\""
		domain := "\"\""
		port := "\":8080\""
		autoTLS := "false"
		if len(call.Args) > 0 {
			dir = g.genExpr(call.Args[0])
		}
		if len(call.Args) > 1 {
			domain = g.genExpr(call.Args[1])
		}
		if len(call.Args) > 2 {
			port = g.genExpr(call.Args[2])
		}
		if len(call.Args) > 3 {
			autoTLS = g.genExpr(call.Args[3])
		}
		return fmt.Sprintf("web.ServeSite(%s, %s, %s, %s)", dir, domain, port, autoTLS)
	default:
		args := []string{}
		for _, a := range call.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("%s(%s)", call.Fn, strings.Join(args, ", "))
	}
}

func mapType(t string) string {
	switch t {
	case "int":
		return "int64"
	case "float":
		return "float64"
	case "str":
		return "string"
	case "bool":
		return "bool"
	case "void", "":
		return ""
	default:
		if strings.HasPrefix(t, "chan[") && strings.HasSuffix(t, "]") {
			inner := t[5 : len(t)-1]
			return fmt.Sprintf("chan %s", mapType(inner))
		}
		return t
	}
}

func mapOp(op string) string {
	switch op {
	case "add":
		return "+"
	case "sub":
		return "-"
	case "mul":
		return "*"
	case "div":
		return "/"
	case "eq":
		return "=="
	case "neq":
		return "!="
	case "gt":
		return ">"
	case "lt":
		return "<"
	case "gte":
		return ">="
	case "lte":
		return "<="
	case "and":
		return "&&"
	case "or":
		return "||"
	default:
		return op
	}
}

func (g *Generator) writeIndent() {
	for i := 0; i < g.indent; i++ {
		g.sb.WriteString("\t")
	}
}
