package codegen

import (
	"fmt"
	"strings"

	"liaf/pkg/ast"
	"liaf/pkg/checker"
)

type Generator struct {
	mod         *ast.Module
	sb          strings.Builder
	indent      int
	info        *checker.Info
	serial      int
	curOnErrVar string
	curRetType  ast.Type
}

func New(mod *ast.Module) *Generator {
	info, _ := checker.Check(mod, "")
	return &Generator{mod: mod, info: info}
}

func (g *Generator) Generate() string {
	g.sb.WriteString("// Code generated by liafc (Language for AI First). DO NOT EDIT.\n")
	g.sb.WriteString("package main\n\n")
	g.sb.WriteString("import (\n")
	g.sb.WriteString("\t\"encoding/json\"\n")
	g.sb.WriteString("\t\"fmt\"\n")
	g.sb.WriteString("\t\"strconv\"\n")
	g.sb.WriteString("\t\"strings\"\n")
	g.sb.WriteString("\t\"time\"\n")
	g.sb.WriteString("\t\"liaf/pkg/web\"\n")
	g.sb.WriteString("\trt \"liaf/pkg/runtime\"\n")
	g.sb.WriteString(")\n\n")

	g.sb.WriteString("var (\n")
	g.sb.WriteString("\t_ = json.Marshal\n")
	g.sb.WriteString("\t_ = fmt.Sprint\n")
	g.sb.WriteString("\t_ = strconv.FormatInt\n")
	g.sb.WriteString("\t_ = strings.Builder{}\n")
	g.sb.WriteString("\t_ = time.Sleep\n")
	g.sb.WriteString("\t_ = web.ServeSite\n")
	g.sb.WriteString("\t_ = rt.Exists\n")
	g.sb.WriteString(")\n\n")

	// Built-in helpers da especificação
	g.sb.WriteString("// --- Built-in Helpers da LIAF v0.2 ---\n")
	g.sb.WriteString("func _liaf_concat(args ...interface{}) string {\n")
	g.sb.WriteString("\tvar sb strings.Builder\n")
	g.sb.WriteString("\tfor _, a := range args {\n")
	g.sb.WriteString("\t\tsb.WriteString(fmt.Sprint(a))\n")
	g.sb.WriteString("\t}\n")
	g.sb.WriteString("\treturn sb.String()\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_str_from_int(v int64) string {\n")
	g.sb.WriteString("\treturn strconv.FormatInt(v, 10)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_float_from_int(v int64) float64 {\n")
	g.sb.WriteString("\treturn float64(v)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_int_from_str(s string) int64 {\n")
	g.sb.WriteString("\tres, _ := strconv.ParseInt(strings.TrimSpace(s), 10, 64)\n")
	g.sb.WriteString("\treturn res\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_sleep_ms(ms int64) {\n")
	g.sb.WriteString("\ttime.Sleep(time.Duration(ms) * time.Millisecond)\n")
	g.sb.WriteString("}\n\n")

	for _, decl := range g.mod.Decls {
		switch d := decl.(type) {
		case *ast.StructDecl:
			g.genStruct(d)
		case *ast.FuncDecl:
			g.genFunc(d)
		case *ast.RouteDecl:
			g.genRoute(d)
		}
	}

	return g.sb.String()
}

func (g *Generator) genStruct(s *ast.StructDecl) {
	name := sanitizeIdent(s.Name)
	g.sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	for _, f := range s.Fields {
		g.sb.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", fieldIdent(f.Name), mapType(f.Type), f.Name))
	}
	g.sb.WriteString("}\n\n")
}

func (g *Generator) genFunc(f *ast.FuncDecl) {
	oldOnErr := g.curOnErrVar
	oldRet := g.curRetType
	g.curOnErrVar = f.OnErrVar
	g.curRetType = f.ReturnType
	defer func() {
		g.curOnErrVar = oldOnErr
		g.curRetType = oldRet
	}()

	fnName := sanitizeIdent(f.Name)
	ret := mapType(f.ReturnType)
	if ret != "" {
		ret = " " + ret
	}

	var params []string
	for _, p := range f.Params {
		params = append(params, fmt.Sprintf("%s %s", sanitizeIdent(p.Name), mapType(p.Type)))
	}

	g.sb.WriteString(fmt.Sprintf("func %s(%s)%s {\n", fnName, strings.Join(params, ", "), ret))
	g.indent++

	if f.OnErrVar != "" {
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("_liaf_on_err := func(%s string)%s {\n", sanitizeIdent(f.OnErrVar), ret))
		g.indent++
		for _, stmt := range f.OnErrBody {
			g.genStmt(stmt)
		}
		g.indent--
		g.writeIndent()
		g.sb.WriteString("}\n")
		g.writeIndent()
		g.sb.WriteString("var _ = _liaf_on_err\n")
	}

	for _, stmt := range f.Body {
		g.genStmt(stmt)
	}

	g.indent--
	g.sb.WriteString("}\n\n")
}

func (g *Generator) genRoute(r *ast.RouteDecl) {
	g.serial++
	routeFnName := fmt.Sprintf("_liaf_route_%s_%d", strings.ToLower(r.Method), g.serial)

	oldOnErr := g.curOnErrVar
	oldRet := g.curRetType
	g.curOnErrVar = r.OnErrVar
	g.curRetType = r.ReturnType
	defer func() {
		g.curOnErrVar = oldOnErr
		g.curRetType = oldRet
	}()

	ret := mapType(r.ReturnType)
	if ret != "" {
		ret = " " + ret
	}

	var params []string
	for _, p := range r.Params {
		params = append(params, fmt.Sprintf("%s %s", sanitizeIdent(p.Name), mapType(p.Type)))
	}

	g.sb.WriteString(fmt.Sprintf("func %s(%s)%s {\n", routeFnName, strings.Join(params, ", "), ret))
	g.indent++

	if r.OnErrVar != "" {
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("_liaf_on_err := func(%s string)%s {\n", sanitizeIdent(r.OnErrVar), ret))
		g.indent++
		for _, stmt := range r.OnErrBody {
			g.genStmt(stmt)
		}
		g.indent--
		g.writeIndent()
		g.sb.WriteString("}\n")
		g.writeIndent()
		g.sb.WriteString("var _ = _liaf_on_err\n")
	}

	for _, stmt := range r.Body {
		g.genStmt(stmt)
	}

	g.indent--
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func init() {\n")
	g.sb.WriteString(fmt.Sprintf("\tweb.Register(%q, %q, func(req web.Request) web.Response {\n", strings.ToUpper(r.Method), r.Path))
	g.indent += 2

	// Indice de cada {nome} no padrao do path. Usar sempre o ultimo segmento
	// quebraria rotas como /users/{id}/tasks.
	pathIndex := map[string]int{}
	for i, seg := range strings.Split(strings.Trim(r.Path, "/"), "/") {
		if len(seg) > 2 && strings.HasPrefix(seg, "{") && strings.HasSuffix(seg, "}") {
			pathIndex[seg[1:len(seg)-1]] = i
		}
	}
	partsEmitted := false
	emitParts := func() {
		if partsEmitted {
			return
		}
		partsEmitted = true
		g.writeIndent()
		g.sb.WriteString("parts := strings.Split(strings.Trim(req.Path, \"/\"), \"/\")\n")
		g.writeIndent()
		g.sb.WriteString("_ = parts\n")
	}

	var callArgs []string
	for _, p := range r.Params {
		pName := sanitizeIdent(p.Name)
		pTypeStr := mapType(p.Type)
		if pTypeStr == "web.Request" {
			callArgs = append(callArgs, "req")
			continue
		}
		if idx, isPathParam := pathIndex[p.Name]; isPathParam {
			emitParts()
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("var %s %s\n", pName, pTypeStr))
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("if len(parts) > %d {\n", idx))
			g.indent++
			g.writeIndent()
			if pTypeStr == "int64" {
				g.sb.WriteString(fmt.Sprintf("%s, _ = strconv.ParseInt(parts[%d], 10, 64)\n", pName, idx))
			} else {
				g.sb.WriteString(fmt.Sprintf("%s = parts[%d]\n", pName, idx))
			}
			g.indent--
			g.writeIndent()
			g.sb.WriteString("}\n")
			callArgs = append(callArgs, pName)
			continue
		}
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("var %s %s\n", pName, pTypeStr))
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("if err := json.Unmarshal([]byte(req.Body), &%s); err != nil {\n", pName))
		g.indent++
		g.writeIndent()
		g.sb.WriteString("return web.JSONResponse(400, `{\"error\":\"Invalid JSON body\"}`)\n")
		g.indent--
		g.writeIndent()
		g.sb.WriteString("}\n")
		callArgs = append(callArgs, pName)
	}

	g.writeIndent()
	if ret == " web.Response" {
		g.sb.WriteString(fmt.Sprintf("return %s(%s)\n", routeFnName, strings.Join(callArgs, ", ")))
	} else if ret == " void" || ret == "" {
		g.sb.WriteString(fmt.Sprintf("%s(%s)\n", routeFnName, strings.Join(callArgs, ", ")))
		g.writeIndent()
		g.sb.WriteString("return web.JSONResponse(200, `{\"ok\":true}`)\n")
	} else {
		status := "200"
		if strings.ToUpper(r.Method) == "POST" {
			status = "201"
		}
		g.sb.WriteString(fmt.Sprintf("res := %s(%s)\n", routeFnName, strings.Join(callArgs, ", ")))
		g.writeIndent()
		g.sb.WriteString("data, err := json.Marshal(res)\n")
		g.writeIndent()
		g.sb.WriteString("if err != nil { return web.JSONResponse(500, `{\"error\":\"Serialization error\"}`) }\n")
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("return web.JSONResponse(%s, string(data))\n", status))
	}

	g.indent -= 2
	g.sb.WriteString("\t})\n")
	g.sb.WriteString("}\n\n")
}

// onErrReturn emite o desvio de um try que falhou para o bloco (on-err ...).
// Numa funcao void o handler nao devolve valor, entao `return f()` seria
// invalido em Go: a chamada e o return precisam ficar separados.
func (g *Generator) onErrReturn(resID string) string {
	if mapType(g.curRetType) == "" {
		return fmt.Sprintf("_liaf_on_err(%s.Error)\n%sreturn\n", resID, strings.Repeat("\t", g.indent))
	}
	return fmt.Sprintf("return _liaf_on_err(%s.Error)\n", resID)
}

func (g *Generator) writeIndent() {
	for i := 0; i < g.indent; i++ {
		g.sb.WriteString("\t")
	}
}

func (g *Generator) genStmt(stmt ast.Stmt) {
	g.writeIndent()
	switch s := stmt.(type) {
	case *ast.LoopControl:
		g.sb.WriteString(s.Kind + "\n")
	case *ast.LoopStmt:
		g.serial++
		id := g.serial
		switch s.Kind {
		case "while":
			g.sb.WriteString("for " + g.genExpr(s.Condition) + " {\n")
		case "for-range":
			g.sb.WriteString(fmt.Sprintf("for %s, _liaf_end_%d := int64(%s), int64(%s); %s < _liaf_end_%d; %s++ {\n", sanitizeIdent(s.Name), id, g.genExpr(s.Start), g.genExpr(s.End), sanitizeIdent(s.Name), id, sanitizeIdent(s.Name)))
		case "for-each":
			g.sb.WriteString(fmt.Sprintf("for _, %s := range (%s).Items {\n", sanitizeIdent(s.Name), g.genExpr(s.Collection)))
		}
		g.indent++
		if s.Name != "" {
			g.writeIndent()
			g.sb.WriteString("_ = " + sanitizeIdent(s.Name) + "\n")
		}
		for _, st := range s.Body {
			g.genStmt(st)
		}
		g.indent--
		g.writeIndent()
		g.sb.WriteString("}\n")
	case *ast.MatchStmt:
		g.serial++
		id := fmt.Sprintf("_liaf_result_%d", g.serial)
		g.sb.WriteString(fmt.Sprintf("if %s := %s; %s.OK {\n", id, g.genExpr(s.Value), id))
		g.indent++
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("%s := %s.Value; _ = %s\n", sanitizeIdent(s.OKName), id, sanitizeIdent(s.OKName)))
		for _, st := range s.OK {
			g.genStmt(st)
		}
		g.indent--
		g.writeIndent()
		g.sb.WriteString("} else {\n")
		g.indent++
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("%s := %s.Error; _ = %s\n", sanitizeIdent(s.ErrName), id, sanitizeIdent(s.ErrName)))
		for _, st := range s.Err {
			g.genStmt(st)
		}
		g.indent--
		g.writeIndent()
		g.sb.WriteString("}\n")
	case *ast.LetStmt:
		if tryExpr, ok := s.Value.(*ast.TryExpr); ok {
			g.serial++
			resID := fmt.Sprintf("_liaf_try_%d", g.serial)
			varType := mapType(s.Type)
			g.sb.WriteString(fmt.Sprintf("%s := %s\n", resID, g.genExpr(tryExpr.Expr)))
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("if !%s.OK {\n", resID))
			g.indent++
			g.writeIndent()
			if g.curOnErrVar != "" {
				g.sb.WriteString(g.onErrReturn(resID))
			} else {
				retTypeStr := mapType(g.curRetType)
				g.sb.WriteString(fmt.Sprintf("var _zero %s; _zero.OK = false; _zero.Error = %s.Error; return _zero\n", retTypeStr, resID))
			}
			g.indent--
			g.writeIndent()
			g.sb.WriteString("}\n")
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("var %s %s = %s.Value\n", sanitizeIdent(s.Name), varType, resID))
			g.writeIndent()
			g.sb.WriteString("_ = " + sanitizeIdent(s.Name) + "\n")
			return
		}
		val := g.genExpr(s.Value)
		varType := mapType(s.Type)
		g.sb.WriteString(fmt.Sprintf("var %s %s = %s\n", sanitizeIdent(s.Name), varType, val))
		g.writeIndent()
		g.sb.WriteString("_ = " + sanitizeIdent(s.Name) + "\n")

	case *ast.SetStmt:
		if tryExpr, ok := s.Value.(*ast.TryExpr); ok {
			g.serial++
			resID := fmt.Sprintf("_liaf_try_%d", g.serial)
			g.sb.WriteString(fmt.Sprintf("%s := %s\n", resID, g.genExpr(tryExpr.Expr)))
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("if !%s.OK {\n", resID))
			g.indent++
			g.writeIndent()
			if g.curOnErrVar != "" {
				g.sb.WriteString(g.onErrReturn(resID))
			} else {
				retTypeStr := mapType(g.curRetType)
				g.sb.WriteString(fmt.Sprintf("var _zero %s; _zero.OK = false; _zero.Error = %s.Error; return _zero\n", retTypeStr, resID))
			}
			g.indent--
			g.writeIndent()
			g.sb.WriteString("}\n")
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("%s = %s.Value\n", sanitizeIdent(s.Name), resID))
			return
		}
		val := g.genExpr(s.Value)
		g.sb.WriteString(fmt.Sprintf("%s = %s\n", sanitizeIdent(s.Name), val))

	case *ast.ReturnStmt:
		if s.Value != nil {
			g.sb.WriteString(fmt.Sprintf("return %s\n", g.genExpr(s.Value)))
		} else {
			g.sb.WriteString("return\n")
		}

	case *ast.IfStmt:
		cond := g.genExpr(s.Condition)
		g.sb.WriteString(fmt.Sprintf("if %s {\n", cond))
		g.indent++
		for _, st := range s.Then {
			g.genStmt(st)
		}
		g.indent--

		if len(s.Else) > 0 {
			g.writeIndent()
			g.sb.WriteString("} else {\n")
			g.indent++
			for _, st := range s.Else {
				g.genStmt(st)
			}
			g.indent--
		}
		g.writeIndent()
		g.sb.WriteString("}\n")

	case *ast.SpawnStmt:
		callExpr := g.genExpr(s.Call)
		g.sb.WriteString(fmt.Sprintf("go %s\n", callExpr))

	case *ast.SendStmt:
		ch := g.genExpr(s.Channel)
		val := g.genExpr(s.Value)
		g.sb.WriteString(fmt.Sprintf("%s <- %s\n", ch, val))

	case *ast.ExprStmt:
		if tryExpr, ok := s.Expr.(*ast.TryExpr); ok {
			g.serial++
			resID := fmt.Sprintf("_liaf_try_%d", g.serial)
			g.sb.WriteString(fmt.Sprintf("%s := %s\n", resID, g.genExpr(tryExpr.Expr)))
			g.writeIndent()
			g.sb.WriteString(fmt.Sprintf("if !%s.OK {\n", resID))
			g.indent++
			g.writeIndent()
			if g.curOnErrVar != "" {
				g.sb.WriteString(g.onErrReturn(resID))
			} else {
				retTypeStr := mapType(g.curRetType)
				g.sb.WriteString(fmt.Sprintf("var _zero %s; _zero.OK = false; _zero.Error = %s.Error; return _zero\n", retTypeStr, resID))
			}
			g.indent--
			g.writeIndent()
			g.sb.WriteString("}\n")
			return
		}
		val := g.genExpr(s.Expr)
		if isStandAloneStmt(s.Expr) {
			g.sb.WriteString(fmt.Sprintf("%s\n", val))
		} else {
			g.sb.WriteString(fmt.Sprintf("_ = %s\n", val))
		}
	}
}

func isStandAloneStmt(expr ast.Expr) bool {
	switch expr.(type) {
	case *ast.CallExpr:
		return true
	}
	return false
}

func (g *Generator) genExpr(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.IntLiteral:
		return e.Raw
	case *ast.FloatLiteral:
		return e.Raw
	case *ast.BoolLiteral:
		if e.Value {
			return "true"
		}
		return "false"
	case *ast.StringLiteral:
		return fmt.Sprintf("%q", e.Value)
	case *ast.IdentExpr:
		return sanitizeIdent(e.Name)
	case *ast.CallExpr:
		return g.genCall(e)
	case *ast.BinaryOpExpr:
		return g.genBinaryOp(e)
	case *ast.RecvExpr:
		return fmt.Sprintf("<-%s", g.genExpr(e.Channel))
	case *ast.TryExpr:
		return fmt.Sprintf("(%s).Value", g.genExpr(e.Expr))
	default:
		return ""
	}
}

func (g *Generator) genCall(c *ast.CallExpr) string {
	if value, ok := g.libraryCall(c); ok {
		return value
	}
	switch c.Func {
	case "make-chan", "make_chan":
		elemType := "interface{}"
		if len(c.Args) > 0 {
			if id, ok := c.Args[0].(*ast.IdentExpr); ok {
				elemType = mapTypeName(id.Name)
			}
		}
		return fmt.Sprintf("make(chan %s)", elemType)

	case "println":
		var args []string
		for _, a := range c.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("fmt.Println(%s)", strings.Join(args, ", "))

	case "print":
		var args []string
		for _, a := range c.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("fmt.Print(%s)", strings.Join(args, ", "))

	case "concat":
		var args []string
		for _, a := range c.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("_liaf_concat(%s)", strings.Join(args, ", "))

	case "not":
		if len(c.Args) > 0 {
			return fmt.Sprintf("!(%s)", g.genExpr(c.Args[0]))
		}
		return "false"

	case "str-from-int", "str_from_int":
		if len(c.Args) > 0 {
			return fmt.Sprintf("_liaf_str_from_int(int64(%s))", g.genExpr(c.Args[0]))
		}
		return `""`

	case "float-from-int", "float_from_int":
		if len(c.Args) > 0 {
			return fmt.Sprintf("_liaf_float_from_int(int64(%s))", g.genExpr(c.Args[0]))
		}
		return "0.0"

	case "int-from-str", "int_from_str":
		if len(c.Args) > 0 {
			return fmt.Sprintf("_liaf_int_from_str(%s)", g.genExpr(c.Args[0]))
		}
		return "0"

	case "sleep-ms", "sleep_ms":
		if len(c.Args) > 0 {
			return fmt.Sprintf("_liaf_sleep_ms(int64(%s))", g.genExpr(c.Args[0]))
		}
		return ""

	case "serve-site", "serve_site":
		var args []string
		for _, a := range c.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("web.ServeSite(%s)", strings.Join(args, ", "))

	default:
		var args []string
		for _, a := range c.Args {
			args = append(args, g.genExpr(a))
		}
		return fmt.Sprintf("%s(%s)", sanitizeIdent(c.Func), strings.Join(args, ", "))
	}
}

func (g *Generator) genBinaryOp(b *ast.BinaryOpExpr) string {
	left := g.genExpr(b.Left)
	right := g.genExpr(b.Right)

	switch b.Op {
	case "add":
		return fmt.Sprintf("(%s + %s)", left, right)
	case "sub":
		return fmt.Sprintf("(%s - %s)", left, right)
	case "mul":
		return fmt.Sprintf("(%s * %s)", left, right)
	case "div":
		return fmt.Sprintf("(%s / %s)", left, right)
	case "eq":
		return fmt.Sprintf("(%s == %s)", left, right)
	case "neq":
		return fmt.Sprintf("(%s != %s)", left, right)
	case "gt":
		return fmt.Sprintf("(%s > %s)", left, right)
	case "lt":
		return fmt.Sprintf("(%s < %s)", left, right)
	case "gte":
		return fmt.Sprintf("(%s >= %s)", left, right)
	case "lte":
		return fmt.Sprintf("(%s <= %s)", left, right)
	case "and":
		return fmt.Sprintf("(%s && %s)", left, right)
	case "or":
		return fmt.Sprintf("(%s || %s)", left, right)
	default:
		return fmt.Sprintf("%s(%s, %s)", sanitizeIdent(b.Op), left, right)
	}
}

func sanitizeIdent(id string) string {
	id = strings.ReplaceAll(id, "_", "_u_")
	id = strings.ReplaceAll(id, "-", "_h_")
	switch id {
	case "break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough", "for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range", "return", "select", "struct", "switch", "type", "var", "fmt", "rt", "web", "time", "strings", "strconv", "true", "false", "nil":
		return "_liaf_user_" + id
	}
	return id
}

func fieldIdent(id string) string { return "Field_" + sanitizeIdent(id) }

func mapType(t ast.Type) string {
	if t == nil {
		return ""
	}
	switch ty := t.(type) {
	case *ast.PrimitiveType:
		return mapTypeName(ty.Name)
	case *ast.NamedType:
		if ty.Name == "Request" || ty.Name == "Response" {
			return "web." + ty.Name
		}
		return sanitizeIdent(ty.Name)
	case *ast.AppliedType:
		switch ty.Constructor {
		case "chan":
			if len(ty.Args) > 0 {
				return fmt.Sprintf("chan %s", mapType(ty.Args[0]))
			}
			return "chan interface{}"
		case "list":
			if len(ty.Args) > 0 {
				return fmt.Sprintf("*rt.List[%s]", mapType(ty.Args[0]))
			}
			return "[]interface{}"
		case "map":
			if len(ty.Args) >= 2 {
				return fmt.Sprintf("map[%s]%s", mapType(ty.Args[0]), mapType(ty.Args[1]))
			}
			return "map[string]interface{}"
		case "result":
			return fmt.Sprintf("rt.Result[%s,%s]", mapType(ty.Args[0]), mapType(ty.Args[1]))
		default:
			return sanitizeIdent(ty.Constructor)
		}
	default:
		return "interface{}"
	}
}

func mapTypeName(name string) string {
	switch name {
	case "int":
		return "int64"
	case "float":
		return "float64"
	case "str":
		return "string"
	case "bool":
		return "bool"
	case "void":
		return ""
	default:
		return sanitizeIdent(name)
	}
}
