package codegen

import (
	"fmt"
	"sort"
	"strings"

	"liaf/pkg/ast"
	"liaf/pkg/checker"
)

type Generator struct {
	mod         *ast.Module
	sb          strings.Builder
	indent      int
	info        *checker.Info
	serial      int
	curOnErrVar string
	curRetType  ast.Type
	// extraImports são imports pedidos por builtins usados (Builtin.GoImport).
	extraImports map[string]bool
}

const extraImportsMarker = "\t// liaf:extra-imports\n"


func New(mod *ast.Module) *Generator {
	info, _ := checker.Check(mod, "")
	return &Generator{mod: mod, info: info, extraImports: map[string]bool{}}
}

func (g *Generator) Generate() string {
	g.sb.WriteString("// Code generated by liafc (Language for AI First). DO NOT EDIT.\n")
	g.sb.WriteString("package main\n\n")
	g.sb.WriteString("import (\n")
	g.sb.WriteString("\t\"encoding/json\"\n")
	g.sb.WriteString("\t\"fmt\"\n")
	g.sb.WriteString("\t\"strconv\"\n")
	g.sb.WriteString("\t\"strings\"\n")
	g.sb.WriteString("\t\"time\"\n")
	g.sb.WriteString("\t\"liaf/pkg/web\"\n")
	g.sb.WriteString("\trt \"liaf/pkg/runtime\"\n")
	g.sb.WriteString(extraImportsMarker)
	g.sb.WriteString(")\n\n")

	g.sb.WriteString("var (\n")
	g.sb.WriteString("\t_ = json.Marshal\n")
	g.sb.WriteString("\t_ = fmt.Sprint\n")
	g.sb.WriteString("\t_ = strconv.FormatInt\n")
	g.sb.WriteString("\t_ = strings.Builder{}\n")
	g.sb.WriteString("\t_ = time.Sleep\n")
	g.sb.WriteString("\t_ = web.ServeSite\n")
	g.sb.WriteString("\t_ = rt.Exists\n")
	g.sb.WriteString(")\n\n")

	// Built-in helpers da especificação
	g.sb.WriteString("// --- Built-in Helpers da LIAF v0.2 ---\n")
	g.sb.WriteString("func _liaf_concat(args ...interface{}) string {\n")
	g.sb.WriteString("\tvar sb strings.Builder\n")
	g.sb.WriteString("\tfor _, a := range args {\n")
	g.sb.WriteString("\t\tsb.WriteString(fmt.Sprint(a))\n")
	g.sb.WriteString("\t}\n")
	g.sb.WriteString("\treturn sb.String()\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_fmt(pattern string, args ...interface{}) string {\n")
	g.sb.WriteString("\tvar sb strings.Builder\n")
	g.sb.WriteString("\targIdx := 0\n")
	g.sb.WriteString("\tfor i := 0; i < len(pattern); {\n")
	g.sb.WriteString("\t\tif i+1 < len(pattern) && pattern[i] == '{' && pattern[i+1] == '{' {\n")
	g.sb.WriteString("\t\t\tsb.WriteByte('{')\n")
	g.sb.WriteString("\t\t\ti += 2\n")
	g.sb.WriteString("\t} else if i+1 < len(pattern) && pattern[i] == '}' && pattern[i+1] == '}' {\n")
	g.sb.WriteString("\t\t\tsb.WriteByte('}')\n")
	g.sb.WriteString("\t\t\ti += 2\n")
	g.sb.WriteString("\t} else if i+1 < len(pattern) && pattern[i] == '{' && pattern[i+1] == '}' {\n")
	g.sb.WriteString("\t\t\tif argIdx < len(args) {\n")
	g.sb.WriteString("\t\t\t\tsb.WriteString(fmt.Sprint(args[argIdx]))\n")
	g.sb.WriteString("\t\t\t\targIdx++\n")
	g.sb.WriteString("\t\t\t} else {\n")
	g.sb.WriteString("\t\t\t\tsb.WriteString(\"{}\")\n")
	g.sb.WriteString("\t\t\t}\n")
	g.sb.WriteString("\t\t\ti += 2\n")
	g.sb.WriteString("\t} else {\n")
	g.sb.WriteString("\t\t\tsb.WriteByte(pattern[i])\n")
	g.sb.WriteString("\t\t\ti++\n")
	g.sb.WriteString("\t\t}\n")
	g.sb.WriteString("\t}\n")
	g.sb.WriteString("\treturn sb.String()\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_str_from_int(v int64) string {\n")
	g.sb.WriteString("\treturn strconv.FormatInt(v, 10)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_float_from_int(v int64) float64 {\n")
	g.sb.WriteString("\treturn float64(v)\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_int_from_str(s string) int64 {\n")
	g.sb.WriteString("\tres, _ := strconv.ParseInt(strings.TrimSpace(s), 10, 64)\n")
	g.sb.WriteString("\treturn res\n")
	g.sb.WriteString("}\n\n")

	g.sb.WriteString("func _liaf_sleep_ms(ms int64) {\n")
	g.sb.WriteString("\ttime.Sleep(time.Duration(ms) * time.Millisecond)\n")
	g.sb.WriteString("}\n\n")

	for _, decl := range g.mod.Decls {
		switch d := decl.(type) {
		case *ast.StructDecl:
			g.genStruct(d)
		case *ast.FuncDecl:
			g.genFunc(d)
		case *ast.RouteDecl:
			g.genRoute(d)
		case *ast.WSRouteDecl:
			g.genWSRoute(d)
		}
	}

	return strings.Replace(g.sb.String(), extraImportsMarker, g.importLines(), 1)
}

func (g *Generator) importLines() string {
	lines := make([]string, 0, len(g.extraImports))
	for imp := range g.extraImports {
		lines = append(lines, "\t"+imp+"\n")
	}
	sort.Strings(lines)
	return strings.Join(lines, "")
}

func (g *Generator) genStruct(s *ast.StructDecl) {
	name := sanitizeIdent(s.Name)
	g.sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	for _, f := range s.Fields {
		g.sb.WriteString(fmt.Sprintf("\t%s %s `json:%q`\n", fieldIdent(f.Name), mapType(f.Type), f.Name))
	}
	g.sb.WriteString("}\n\n")
}

func (g *Generator) genFunc(f *ast.FuncDecl) {
	oldOnErr := g.curOnErrVar
	oldRet := g.curRetType
	g.curOnErrVar = f.OnErrVar
	g.curRetType = f.ReturnType
	defer func() {
		g.curOnErrVar = oldOnErr
		g.curRetType = oldRet
	}()

	fnName := sanitizeIdent(f.Name)
	ret := mapType(f.ReturnType)
	if ret != "" {
		ret = " " + ret
	}

	var params []string
	for _, p := range f.Params {
		params = append(params, fmt.Sprintf("%s %s", sanitizeIdent(p.Name), mapType(p.Type)))
	}

	g.sb.WriteString(fmt.Sprintf("func %s(%s)%s {\n", fnName, strings.Join(params, ", "), ret))
	g.indent++

	if f.OnErrVar != "" {
		g.writeIndent()
		g.sb.WriteString(fmt.Sprintf("_liaf_on_err := func(%s string)%s {\n", sanitizeIdent(f.OnErrVar), ret))
		g.indent++
		for _, stmt := range f.OnErrBody {
			g.genStmt(stmt)
		}
		g.indent--
		g.writeIndent()
		g.sb.WriteString("}\n")
		g.writeIndent()
		g.sb.WriteString("var _ = _liaf_on_err\n")
	}

	for _, stmt := range f.Body {
		g.genStmt(stmt)
	}

	g.indent--
	g.sb.WriteString("}\n\n")
}
